@host=localhost
@device_ip=sapphire5-dev.int.cpacket.com
@device_id=6a0ba884b56f9ad0396dcd9d


###
//add a cstor
# @curl-insecure 
POST https://{{host}}/rt/data/cstor/modify HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{"ip":"{{device_ip}}","name":"sap","auth_type":"basic","verify_ssl":false}


###
//auth a cstor
# @curl-insecure 
POST https://{{host}}/api/cstor/devauth/modify HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{"device_id":"{{device_id}}","password":"cpacketpw","username":"cpacket"}


###
//delete a cstor
# @curl-insecure 
POST https://{{host}}/rt/data/cstor/delete HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{
	"ids": ["{{device_id}}"]
}
