###

# @curl-insecure 
GET https://{{HOST}}/api/info/v1 HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}

###
//get cerchain file
# @curl-insecure 
GET https://{{HOST}}/api/crypto/v1/tls/authorities HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}

###
//upload cerchain file
# @curl-insecure 
PUT https://{{HOST}}/api/crypto/v1/tls/authorities HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="bundle"; filename="certchain.cer"
Content-Type: text/plain

< /home/jchen/Downloads/Automation-35.int.cpacket.com/certchain.cer

------WebKitFormBoundary{{$timestamp}}--

###
//delete cerchain file
# @curl-insecure 
DELETE https://{{HOST}}/api/crypto/v1/tls/authorities HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}

###
//tls check
# @curl-insecure 
PUT https://{{HOST}}/api/crypto/v1/tls/check HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{
    "domain": "Automation-35.int.cpacket.com"
}

###
//add tls syslog receiver
# @curl-insecure 
POST https://{{HOST}}/api/logs/v1/receivers/syslog HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{
	"host": "Automation-35.int.cpacket.com",
	"port": 2001,
	"status": "enabled",
	"transport": "tcpTls",
	"filters": [],
	"verify": true
}

###
//get tls syslog receiver
# @curl-insecure 
GET https://{{HOST}}/api/logs/v1/receivers/syslog HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}

###

@receiver_id=88835cc0-9147-416e-a5ee-4a9aec1a435c
//update a syslog receiver
# @curl-insecure 
PUT https://{{HOST}}/api/logs/v1/receivers/syslog/{{receiver_id}} HTTP/1.1
Authorization: Basic {{CCLEAR_USERNAME}}:{{CCLEAR_PASSWORD}}
Content-Type: application/json

{
	"host": "automation-35.int.cpacket.com",
	"port": 6666,
	"status": "enabled",
	"transport": "tcpTls",
	"filters": [],
	"verify": false
}

